[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.build]
cmds = [
  "dotnet restore ./SalaryManagementAPI/SalaryManagementAPI.csproj",
  "dotnet publish -c Release -o out ./SalaryManagementAPI/SalaryManagementAPI.csproj"
]

[start]
cmd = "dotnet ./out/SalaryManagementAPI.dll"
