// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SalaryManagementAPI.Data;

#nullable disable

namespace SalaryManagementAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SalaryManagementAPI.Models.BangThueTNCN", b =>
                {
                    b.Property<int>("Bac")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Bac"));

                    b.Property<decimal?>("MucDen")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MucTu")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SoTienGiamTru")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<DateTime>("ThoiGianHieuLuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TyLe")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Bac");

                    b.ToTable("BangThueTNCN", (string)null);
                });

            modelBuilder.Entity("SalaryManagementAPI.Models.BaoHiem", b =>
                {
                    b.Property<int>("MaBH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaBH"));

                    b.Property<decimal>("BHTN")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<decimal>("BHXH")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<decimal>("BHYT")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<int>("MaNV")
                        .HasColumnType("integer");

                    b.Property<int>("Nam")
                        .HasColumnType("integer");

                    b.Property<int>("Thang")
                        .HasColumnType("integer");

                    b.Property<decimal>("TongBH")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.HasKey("MaBH");

                    b.HasIndex("MaNV");

                    b.ToTable("BaoHiem", (string)null);
                });

            modelBuilder.Entity("SalaryManagementAPI.Models.ChamCong", b =>
                {
                    b.Property<int>("MaCC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaCC"));

                    b.Property<int>("MaNV")
                        .HasColumnType("integer");

                    b.Property<int>("Nam")
                        .HasColumnType("integer");

                    b.Property<int>("SoGioTangCa")
                        .HasColumnType("integer");

                    b.Property<int>("SoNgayCong")
                        .HasColumnType("integer");

                    b.Property<int>("SoNgayNghiCoPhep")
                        .HasColumnType("integer");

                    b.Property<int>("SoNgayNghiKhongPhep")
                        .HasColumnType("integer");

                    b.Property<int>("Thang")
                        .HasColumnType("integer");

                    b.HasKey("MaCC");

                    b.HasIndex("MaNV");

                    b.ToTable("ChamCong", (string)null);
                });

            modelBuilder.Entity("SalaryManagementAPI.Models.ChiTietLuong", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaChiTiet"));

                    b.Property<decimal>("HeSoLuong")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<decimal>("LuongCoBan")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<decimal>("LuongThucLanh")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<decimal>("LuongTruocKhauTru")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<int>("MaLuong")
                        .HasColumnType("integer");

                    b.Property<decimal>("TongPhat")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<decimal>("TongPhuCap")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<decimal>("TongThuong")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.HasKey("MaChiTiet");

                    b.HasIndex("MaLuong")
                        .IsUnique();

                    b.ToTable("ChiTietLuong", (string)null);
                });

            modelBuilder.Entity("SalaryManagementAPI.Models.ChucVu", b =>
                {
                    b.Property<int>("MaChucVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaChucVu"));

                    b.Property<decimal>("HeSoLuong")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaChucVu");

                    b.ToTable("ChucVu", (string)null);
                });

            modelBuilder.Entity("SalaryManagementAPI.Models.GiamTruThueTNCN", b =>
                {
                    b.Property<int>("MaGiamTru")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaGiamTru"));

                    b.Property<string>("LoaiGiamTru")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("MaNV")
                        .HasColumnType("integer");

                    b.Property<int>("Nam")
                        .HasColumnType("integer");

                    b.Property<decimal>("SoTien")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<int>("Thang")
                        .HasColumnType("integer");

                    b.HasKey("MaGiamTru");

                    b.HasIndex("MaNV");

                    b.ToTable("GiamTruThueTNCN", (string)null);
                });

            modelBuilder.Entity("SalaryManagementAPI.Models.HopDong", b =>
                {
                    b.Property<int>("MaHD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaHD"));

                    b.Property<string>("LoaiHopDong")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaNV")
                        .HasColumnType("integer");

                    b.Property<decimal>("MucLuongCoBan")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MaHD");

                    b.HasIndex("MaNV");

                    b.ToTable("HopDong", (string)null);
                });

            modelBuilder.Entity("SalaryManagementAPI.Models.Luong", b =>
                {
                    b.Property<int>("MaLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaLuong"));

                    b.Property<int>("MaNV")
                        .HasColumnType("integer");

                    b.Property<int>("Nam")
                        .HasColumnType("integer");

                    b.Property<int>("NgayTinhLuong")
                        .HasColumnType("integer");

                    b.Property<int>("Thang")
                        .HasColumnType("integer");

                    b.Property<decimal>("TongLuong")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.HasKey("MaLuong");

                    b.HasIndex("MaNV");

                    b.ToTable("Luong", (string)null);
                });

            modelBuilder.Entity("SalaryManagementAPI.Models.NguoiDung", b =>
                {
                    b.Property<string>("TenDangNhap")
                        .HasColumnType("text");

                    b.Property<int>("MaNV")
                        .HasColumnType("integer");

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("integer");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TenDangNhap");

                    b.HasIndex("MaNV");

                    b.HasIndex("MaVaiTro");

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("SalaryManagementAPI.Models.NhanVien", b =>
                {
                    b.Property<int>("MaNV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaNV"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DienThoai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaChucVu")
                        .HasColumnType("integer");

                    b.Property<int>("MaPhong")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MaNV");

                    b.HasIndex("MaChucVu");

                    b.HasIndex("MaPhong");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("SalaryManagementAPI.Models.PhongBan", b =>
                {
                    b.Property<int>("MaPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaPhong"));

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaPhong");

                    b.ToTable("PhongBan", (string)null);
                });

            modelBuilder.Entity("SalaryManagementAPI.Models.PhuCap", b =>
                {
                    b.Property<int>("MaPC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaPC"));

                    b.Property<string>("LoaiPhuCap")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaNV")
                        .HasColumnType("integer");

                    b.Property<int>("Nam")
                        .HasColumnType("integer");

                    b.Property<decimal>("SoTien")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<int>("Thang")
                        .HasColumnType("integer");

                    b.HasKey("MaPC");

                    b.HasIndex("MaNV");

                    b.ToTable("PhuCap", (string)null);
                });

            modelBuilder.Entity("SalaryManagementAPI.Models.ThueTNCN", b =>
                {
                    b.Property<int>("MaThue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaThue"));

                    b.Property<int>("BacThue")
                        .HasColumnType("integer");

                    b.Property<int>("MaNV")
                        .HasColumnType("integer");

                    b.Property<int>("Nam")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayTinhThue")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Thang")
                        .HasColumnType("integer");

                    b.Property<decimal>("ThuNhapChiuThue")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<decimal>("ThuePhaiDong")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.HasKey("MaThue");

                    b.HasIndex("BacThue");

                    b.HasIndex("MaNV");

                    b.ToTable("ThueTNCN", (string)null);
                });

            modelBuilder.Entity("SalaryManagementAPI.Models.ThuongPhat", b =>
                {
                    b.Property<int>("MaTP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaTP"));

                    b.Property<string>("Loai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaNV")
                        .HasColumnType("integer");

                    b.Property<int>("Nam")
                        .HasColumnType("integer");

                    b.Property<decimal>("SoTien")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<int>("Thang")
                        .HasColumnType("integer");

                    b.HasKey("MaTP");

                    b.HasIndex("MaNV");

                    b.ToTable("ThuongPhat", (string)null);
                });

            modelBuilder.Entity("SalaryManagementAPI.Models.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaVaiTro"));

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaVaiTro");

                    b.ToTable("VaiTro", (string)null);
                });

            modelBuilder.Entity("SalaryManagementAPI.Models.BaoHiem", b =>
                {
                    b.HasOne("SalaryManagementAPI.Models.NhanVien", "NhanVien")
                        .WithMany("BaoHiems")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("SalaryManagementAPI.Models.ChamCong", b =>
                {
                    b.HasOne("SalaryManagementAPI.Models.NhanVien", "NhanVien")
                        .WithMany("ChamCongs")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("SalaryManagementAPI.Models.ChiTietLuong", b =>
                {
                    b.HasOne("SalaryManagementAPI.Models.Luong", "Luong")
                        .WithOne("ChiTietLuong")
                        .HasForeignKey("SalaryManagementAPI.Models.ChiTietLuong", "MaLuong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Luong");
                });

            modelBuilder.Entity("SalaryManagementAPI.Models.GiamTruThueTNCN", b =>
                {
                    b.HasOne("SalaryManagementAPI.Models.NhanVien", "NhanVien")
                        .WithMany("GiamTruThueTNCNs")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("SalaryManagementAPI.Models.HopDong", b =>
                {
                    b.HasOne("SalaryManagementAPI.Models.NhanVien", "NhanVien")
                        .WithMany("HopDongs")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("SalaryManagementAPI.Models.Luong", b =>
                {
                    b.HasOne("SalaryManagementAPI.Models.NhanVien", "NhanVien")
                        .WithMany("Luongs")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("SalaryManagementAPI.Models.NguoiDung", b =>
                {
                    b.HasOne("SalaryManagementAPI.Models.NhanVien", "NhanVien")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalaryManagementAPI.Models.VaiTro", "VaiTro")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("SalaryManagementAPI.Models.NhanVien", b =>
                {
                    b.HasOne("SalaryManagementAPI.Models.ChucVu", "ChucVu")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaChucVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalaryManagementAPI.Models.PhongBan", "PhongBan")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChucVu");

                    b.Navigation("PhongBan");
                });

            modelBuilder.Entity("SalaryManagementAPI.Models.PhuCap", b =>
                {
                    b.HasOne("SalaryManagementAPI.Models.NhanVien", "NhanVien")
                        .WithMany("PhuCaps")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("SalaryManagementAPI.Models.ThueTNCN", b =>
                {
                    b.HasOne("SalaryManagementAPI.Models.BangThueTNCN", "BacThueInfo")
                        .WithMany("ThueTNCNs")
                        .HasForeignKey("BacThue")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalaryManagementAPI.Models.NhanVien", "NhanVien")
                        .WithMany("ThueTNCNs")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BacThueInfo");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("SalaryManagementAPI.Models.ThuongPhat", b =>
                {
                    b.HasOne("SalaryManagementAPI.Models.NhanVien", "NhanVien")
                        .WithMany("ThuongPhats")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("SalaryManagementAPI.Models.BangThueTNCN", b =>
                {
                    b.Navigation("ThueTNCNs");
                });

            modelBuilder.Entity("SalaryManagementAPI.Models.ChucVu", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("SalaryManagementAPI.Models.Luong", b =>
                {
                    b.Navigation("ChiTietLuong");
                });

            modelBuilder.Entity("SalaryManagementAPI.Models.NhanVien", b =>
                {
                    b.Navigation("BaoHiems");

                    b.Navigation("ChamCongs");

                    b.Navigation("GiamTruThueTNCNs");

                    b.Navigation("HopDongs");

                    b.Navigation("Luongs");

                    b.Navigation("NguoiDungs");

                    b.Navigation("PhuCaps");

                    b.Navigation("ThueTNCNs");

                    b.Navigation("ThuongPhats");
                });

            modelBuilder.Entity("SalaryManagementAPI.Models.PhongBan", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("SalaryManagementAPI.Models.VaiTro", b =>
                {
                    b.Navigation("NguoiDungs");
                });
#pragma warning restore 612, 618
        }
    }
}
